# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20180804_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placename', models.CharField(max_length=200)),
                ('n0', models.DecimalField(decimal_places=3, max_digits=5)),
                ('n1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('n2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('n3', models.DecimalField(decimal_places=3, max_digits=5)),
                ('n4', models.DecimalField(decimal_places=3, max_digits=5)),
                ('n5', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='number',
        ),
        migrations.AddField(
            model_name='place',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
