# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20180805_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pn',
            name='n5',
        ),
    ]
