# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_pn_n5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pn',
            name='Placename',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
