# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20180805_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pn',
            old_name='Placename',
            new_name='Placename1',
        ),
    ]
