# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20180805_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pn',
            name='id',
        ),
        migrations.AlterField(
            model_name='place',
            name='Placename',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pn',
            name='Placename1',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
