# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20180805_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
