# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('Placename', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
