# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_delete_pn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pn',
            fields=[
                ('Placename1', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('n0', models.DecimalField(decimal_places=3, max_digits=5)),
                ('n1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('n2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('n3', models.DecimalField(decimal_places=3, max_digits=5)),
                ('n4', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
